opam-version: "2.0"
maintainer: "palmskog@gmail.com"
version: "dev"

homepage: "https://github.com/coq-community/stalmarck"
dev-repo: "git+https://github.com/coq-community/stalmarck.git"
bug-reports: "https://github.com/coq-community/stalmarck/issues"
license: "LGPL-2.1-or-later"

synopsis: "Verified tool for proving tautologies using Stålmarck's algorithm"

build: ["dune" "build" "-p" name "-j" jobs]
depends: [
  "ocaml" {>= "4.09.0"}
  "dune" {>= "2.8"}
  "coq-stalmarck-tactic" {= version}
]

authors: [
  "Pierre Letouzey"
  "Laurent Théry"
]
